GestaoTarefasIPG/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GestaoTarefasIPG.Models
{
    public class Funcionario
    {
        public int FuncionarioID { get; set; }
        [Required(ErrorMessage = "Por favor, insira um nome")]
        [StringLength(248)]
        [Display(Name = "Nome:")]
        public string Nome { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Email:")]
        public string Email { get; set; }
        [Required]
        [Phone]
        [Display(Name = "Telemovel:")]
        public string Telemovel { get; set; }

        public Escola Escola { get; set; }
        public int EscolaId { get; set; }
    }
}

GestaoTarefasIPG/Models/FuncionariosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GestaoTarefasIPG.Models
{
    public class FuncionariosViewModel
    {
        public IEnumerable<Funcionario> Funcionarios { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public int FirstPageShow { get; set; }
        public int LastPageShow { get; set; }
        public int FirstPage { get; set; }
        public int LastPage { get; set; }
        public string CurrentSortOrder { get; set; }
        public string CurrentSearchOption { get; set; }
        public string CurrentSearchString { get; set; }
    }
}

GestaoTarefasIPG/Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoTarefasIPG.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly GestaoTarefasIPGDbContext _context;

        private const int NUMBER_OF_PRODUCTS_PER_PAGE = 10;
        private const int NUMBER_OF_PAGES_BEFORE_AND_AFTER = 1;
        public FuncionariosController(GestaoTarefasIPGDbContext context)
        {
            _context = context;
        }

        // GET: Funcionarios
        public IActionResult Index(int page = 1, string sortOrder = "Nome", string searchString = null, string searchOption = null)
        {
            decimal numberProducts = _context.Funcionario.Count();
            FuncionariosViewModel vm = new FuncionariosViewModel
            {
                Funcionarios = _context.Funcionario
                .Take((int)numberProducts),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(numberProducts / NUMBER_OF_PRODUCTS_PER_PAGE),
                FirstPageShow = Math.Max(2, page - NUMBER_OF_PAGES_BEFORE_AND_AFTER),
            };
            var searchOptionList = new List<string>();

            searchOptionList.Add("Nome");
            searchOptionList.Add("Email");
            searchOptionList.Add("Telemovel");

            ViewBag.searchOption = new SelectList(searchOptionList);

            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(searchOption))
            {
                vm.CurrentSearchString = searchString;
                switch (searchOption)
                {
                    case "Nome":
                        vm.Funcionarios = vm.Funcionarios.Where(p => p.Nome.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Nome";
                        break;
                    case "Email":
                        vm.Funcionarios = vm.Funcionarios.Where(p => p.Email.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Email";
                        break;
                    case "Telemovel":
                        vm.Funcionarios = vm.Funcionarios.Where(p => p.Telemovel.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Telemovel";
                        break;
                }
            }
            ViewBag.NomeSortParm = sortOrder == "Nome" ? "Nome_Desc" : "Nome";
            ViewBag.SiglaSortParm = sortOrder == "Email" ? "Email_Desc" : "Email";
            ViewBag.LocalizacaoSortParm = sortOrder == "Telemovel" ? "Telemovel_Desc" : "Telemovel";
            switch (sortOrder)
            {
                case "Nome_Desc":
                    vm.Funcionarios = vm.Funcionarios.OrderByDescending(p => p.Nome);
                    vm.CurrentSortOrder = "Nome_Desc";
                    break;
                case "Email":
                    vm.Funcionarios = vm.Funcionarios.OrderBy(p => p.Email);
                    vm.CurrentSortOrder = "Email";
                    break;
                case "Email_Desc":
                    vm.Funcionarios = vm.Funcionarios.OrderByDescending(p => p.Email);
                    vm.CurrentSortOrder = "Email_Desc";
                    break;
                case "Telemovel":
                    vm.Funcionarios = vm.Funcionarios.OrderBy(p => p.Telemovel);
                    vm.CurrentSortOrder = "Localizacao";
                    break;
                case "Telemovel_Desc":
                    vm.Funcionarios = vm.Funcionarios.OrderByDescending(p => p.Telemovel);
                    vm.CurrentSortOrder = "Telemovel_Desc";
                    break;
                default:
                    vm.Funcionarios = vm.Funcionarios.OrderBy(p => p.Nome); // ascending by default
                    vm.CurrentSortOrder = "Nome";
                    break;

            }
            vm.TotalPages = (int)Math.Ceiling((decimal)vm.Funcionarios.Count() / NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.Funcionarios = vm.Funcionarios.Skip((page - 1) * NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.Funcionarios = vm.Funcionarios.Take(NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.LastPageShow = Math.Min(vm.TotalPages, page + NUMBER_OF_PAGES_BEFORE_AND_AFTER);
            vm.FirstPage = 1;
            vm.LastPage = vm.TotalPages;
            return View(vm);
        }

        // GET: Funcionarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionario
                .FirstOrDefaultAsync(m => m.FuncionarioID == id);
            if (funcionario == null)
            {
                return NotFound();
            }

            return View(funcionario);
        }

        // GET: Funcionarios/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewData["EscolaId"] = new SelectList(_context.Escola, "EscolaID", "Nome");
            return View();
        }

        // POST: Funcionarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("FuncionarioID,nome,email,telemovel,EscolaId")] Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                if (_context.Escola.FirstOrDefault(m => m.Nome == funcionario.Nome) == null)
                {
                    _context.Add(funcionario);
                    await _context.SaveChangesAsync();
                    return View("Sucesso");
                }
                else
                {
                    ModelState.AddModelError("Nome", "Não é possível adicionar nomes repetidos.");
                    ViewData["EscolaId"] = new SelectList(_context.Escola, "EscolaID", "Nome", funcionario.EscolaId);
                    return View(funcionario);
                }
            }
            else
            {
                return View("Erro");
            }
        }

        // GET: Funcionarios/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionario.FindAsync(id);
            if (funcionario == null)
            {
                return NotFound();
            }
            return View(funcionario);
        }

        // POST: Funcionarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("FuncionarioID,nome,email,telemovel")] Funcionario funcionario)
        {
            if (id != funcionario.FuncionarioID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (_context.Escola.FirstOrDefault(m => m.Nome == funcionario.Nome) == null)
                    {
                        _context.Update(funcionario);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        ModelState.AddModelError("Nome", "Não é possível adicionar nomes repetidos.");
                        return View(funcionario);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FuncionarioExists(funcionario.FuncionarioID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("Sucesso");
            }
            else
            {
                return View("Erro");
            }
        }

        // GET: Funcionarios/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var funcionario = await _context.Funcionario
                .FirstOrDefaultAsync(m => m.FuncionarioID == id);
            if (funcionario == null)
            {
                return NotFound();
            }

            return View(funcionario);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var funcionario = await _context.Funcionario.FindAsync(id);
            _context.Funcionario.Remove(funcionario);
            await _context.SaveChangesAsync();
            return View("Sucesso");
        }

        private bool FuncionarioExists(int id)
        {
            return _context.Funcionario.Any(e => e.FuncionarioID == id);
        }
    }
}

GestaoTarefasIPG/Views/Funcionarios/Create.cshtml
@model GestaoTarefasIPG.Models.Funcionario

@{
    ViewData["Title"] = "Create";
}

<h1>Criar Funcionário</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telemovel" class="control-label"></label>
                <input asp-for="Telemovel" class="form-control" />
                <span asp-validation-for="Telemovel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-dark" /> |
                <a asp-action="Index" class="btn btn-dark">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestaoTarefasIPG/Views/Funcionarios/Delete.cshtml
@model GestaoTarefasIPG.Models.Funcionario

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Funcionário</h1>

<h3>Tem a certeza que pretende apagar isto?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telemovel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telemovel)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="FuncionarioID" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-dark">Voltar</a>
    </form>
</div>

GestaoTarefasIPG/Views/Funcionarios/Details.cshtml
@model GestaoTarefasIPG.Models.Funcionario

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telemovel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telemovel)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.FuncionarioID" class="btn btn-dark">Alterar</a> |
    <a asp-action="Index" class="btn btn-dark">Voltar para a Lista</a>
</div>

GestaoTarefasIPG/Views/Funcionarios/Edit.cshtml
@model GestaoTarefasIPG.Models.Funcionario

@{
    ViewData["Title"] = "Edit";
}

<h1>Alterar Funcionário</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FuncionarioID" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telemovel" class="control-label"></label>
                <input asp-for="Telemovel" class="form-control" />
                <span asp-validation-for="Telemovel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-dark">Voltar para a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestaoTarefasIPG/Views/Funcionarios/Index.cshtml
@*IEnumerable<GestaoTarefasIPG.Models.Funcionario>*@

@model FuncionariosViewModel

@{
    ViewData["Title"] = "Index";
}

<div style="width: 100%; height: 80px">
    <h1 style="float: left">Funcionários</h1>

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow" style="float: right; border-radius: .35rem">
        @using (Html.BeginForm("Index", "Funcionarios", FormMethod.Get))
        {
            <!-- Topbar Search -->
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    @Html.DropDownList("searchOption", null, "Escolher:", new { @style = "border-radius: .35rem" })
                    &nbsp;
                    <!--<input type="text" class="form-control bg-light border-0 small" placeholder="Procure por..." aria-label="Search" aria-describedby="basic-addon2">-->
                    @Html.TextBox("searchString", null, null, new { @class = "form-control bg-light border-0 small", @style = "border-readius: .35rem", @placeholder = "Procure por ..." })
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-danger">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>
        }
    </nav>
</div>

<p>
    <a asp-action="Create" class="btn btn-dark">Criar Novo</a>
</p>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @if (Model.CurrentSortOrder == "Nome")
                {
                    <i class="fas fa-caret-up"></i>
                }
                else if (Model.CurrentSortOrder == "Nome_Desc")
                {
                    <i class="fas fa-caret-down"></i>
                }
                @Html.ActionLink("Nome:", "Index", new
                {
                    sortOrder = ViewBag.NomeSortParm,
                    page = Model.CurrentPage,
                    searchOption = Model.CurrentSearchOption,
                    searchString = Model.CurrentSearchString
                }, new { @style = "color: white" })
            </th>
            <th scope="col">
                @if (Model.CurrentSortOrder == "Email")
                {
                    <i class="fas fa-caret-up"></i>
                }
                else if (Model.CurrentSortOrder == "Email_Desc")
                {
                    <i class="fas fa-caret-down"></i>
                }
                @Html.ActionLink("Email:", "Index", new
                {
                    sortOrder = ViewBag.LocalizacaoSortParm,
                    page = Model.CurrentPage,
                    searchOption = Model.CurrentSearchOption,
                    searchString = Model.CurrentSearchString
                }, new { @style = "color: white" })
            </th>
            <th scope="col">
                @if (Model.CurrentSortOrder == "Telemovel")
                {
                    <i class="fas fa-caret-up"></i>
                }
                else if (Model.CurrentSortOrder == "Telemovel_Desc")
                {
                    <i class="fas fa-caret-down"></i>
                }
                @Html.ActionLink("Telemovel:", "Index", new
                {
                    sortOrder = ViewBag.DescricaoSortParm,
                    page = Model.CurrentPage,
                    searchOption = Model.CurrentSearchOption,
                    searchString = Model.CurrentSearchString
                }, new { @style = "color: white" })
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Funcionarios)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telemovel)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.FuncionarioID" class="btn btn-secondary">Alterar</a> |
                    <a asp-action="Details" asp-route-id="@item.FuncionarioID" class="btn btn-secondary">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.FuncionarioID" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@*
    // TODO: Alter the functioning of the pagination interface
*@
<p>First = @Model.FirstPageShow</p>
<p>Last = @Model.LastPageShow</p>

@if (Model.FirstPage != Model.FirstPageShow)
{
    @Html.ActionLink("" + Model.FirstPage, "Index", new
    {
        sortOrder = Model.CurrentSortOrder,
        page = Model.FirstPage,
        searchOption = Model.CurrentSearchOption,
        searchString = Model.CurrentSearchString
    }, new { @class = "btn btn-secondary" })
}

@for (int i = Model.FirstPageShow; i <= Model.LastPageShow; i++)
{
    @if (i == Model.CurrentPage)
    {
        @Html.ActionLink("" + i, "#", new
        {
            sortOrder = Model.CurrentSortOrder,
            page = i,
            searchOption = Model.CurrentSearchOption,
            searchString = Model.CurrentSearchString
        }, new { @class = "btn btn-dark" })
        <text>&nbsp;</text>
    }
    else
    {
        @Html.ActionLink("" + i, "Index", new
        {
            sortOrder = Model.CurrentSortOrder,
            page = i,
            searchOption = Model.CurrentSearchOption,
            searchString = Model.CurrentSearchString
        }, new { @class = "btn btn-secondary" })
        <text>&nbsp;</text>
    }
}
@if (Model.LastPage != Model.LastPageShow)
{
    @Html.ActionLink("" + Model.LastPage, "Index", new
    {
        sortOrder = Model.CurrentSortOrder,
        page = Model.LastPage,
        searchOption = Model.CurrentSearchOption,
        searchString = Model.CurrentSearchString
    }, new { @class = "btn btn-secondary" })
}