GestaoTarefasIPG/Controllers/CargosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoTarefasIPG.Controllers
{
    public class CargosController : Controller
    {
        private readonly GestaoTarefasIPGDbContext _context;


        private const int NUMBER_OF_PRODUCTS_PER_PAGE = 10;
        private const int NUMBER_OF_PAGES_BEFORE_AND_AFTER = 1;

        public CargosController(GestaoTarefasIPGDbContext context)
        {
            _context = context;
        }

        // GET: Cargos
        
        public async Task<IActionResult> Index(int page = 1, string sortOrder = null, string searchString = null, string searchOption = null)
        {
            decimal numberProducts = _context.Cargo.Count();
            CargosViewModel vm = new CargosViewModel
            {
                Cargos = _context.Cargo
                .Take((int)numberProducts),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(numberProducts / NUMBER_OF_PRODUCTS_PER_PAGE),
                FirstPageShow = Math.Max(2, page - NUMBER_OF_PAGES_BEFORE_AND_AFTER),
            };
            var searchOptionList = new List<string>();
            searchOptionList.Add("Nome");

            ViewBag.searchOption = new SelectList(searchOptionList);

            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(searchOption))
            {
                vm.CurrentSearchString = searchString;
                switch (searchOption)
                {
                    case "Nome":
                        vm.Cargos = vm.Cargos.Where(p => p.NomeCargo.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Nome";
                        break;
                }
            }

                        switch (sortOrder)
            {
                case "Nome":
                    vm.Cargos = vm.Cargos.OrderBy(p => p.NomeCargo); // ascending by default
                    vm.CurrentSortOrder = "Nome";
                    break;
              
            }
            vm.Cargos = vm.Cargos.Skip((page - 1) * NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.Cargos = vm.Cargos.Take(NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.LastPageShow = Math.Min(vm.TotalPages, page + NUMBER_OF_PAGES_BEFORE_AND_AFTER);
            vm.FirstPage = 1;
            vm.LastPage = vm.TotalPages;
            return View(vm);
        }

        // GET: Cargos/Details/5
        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargo = await _context.Cargo
                .FirstOrDefaultAsync(m => m.CargoID == id);
            if (cargo == null)
            {
                return NotFound();
            }

            return View(cargo);
        }

        // GET: Cargos/Create
        [Authorize(Roles ="admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cargos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("CargoID,NomeCargo,NivelCargo")] Cargo cargo)
        {
            
            if (ModelState.IsValid)
            {
                // se isto for null é porque não encontrou nenhum registo na tabela Escola com o mesmo Nome
                if (_context.Cargo.FirstOrDefault(m => m.NomeCargo == cargo.NomeCargo) == null)
                {
                    _context.Add(cargo);
                    await _context.SaveChangesAsync();
                    return View("Sucesso");
                }
                else
                {
                    // aparece a mensagem de erro em baixo do input do Nome
                    ModelState.AddModelError("NomeCargo", "Não é possível adicionar nomes repetidos.");
                    return View(cargo);
                }
            }
            else
            {
                return View("Erro");
            }
        }

        // GET: Cargos/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargo = await _context.Cargo.FindAsync(id);
            if (cargo == null)
            {
                return NotFound();
            }
            return View(cargo);
        }

        // POST: Cargos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("CargoID,NomeCargo,NivelCargo")] Cargo cargo)
        {
            if (id != cargo.CargoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // se isto for null é porque não encontrou nenhum registo na tabela Escola com o mesmo Nome
                    if (_context.Cargo.FirstOrDefault(m => m.NomeCargo == cargo.NomeCargo) == null)
                    {
                        _context.Update(cargo);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        // aparece a mensagem de erro em baixo do input do Nome
                        ModelState.AddModelError("NomeCargo", "Não é possível adicionar nomes repetidos.");
                        return View(cargo);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CargoExists(cargo.CargoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("Sucesso");
            }
            else
            {
                return View("Erro");
            }
            
        }

        // GET: Cargos/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargo = await _context.Cargo
                .FirstOrDefaultAsync(m => m.CargoID == id);
            if (cargo == null)
            {
                return NotFound();
            }

            return View(cargo);
        }

        // POST: Cargos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cargo = await _context.Cargo.FindAsync(id);
            _context.Cargo.Remove(cargo);
            await _context.SaveChangesAsync();
            return View("Sucesso");
        }

        private bool CargoExists(int id)
        {
            return _context.Cargo.Any(e => e.CargoID == id);
        }
    }
}

GestaoTarefasIPG/Controllers/EscolasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoTarefasIPG.Controllers
{
    public class EscolasController : Controller
    {
        private readonly GestaoTarefasIPGDbContext _context;

        private const int NUMBER_OF_PRODUCTS_PER_PAGE = 10;
        private const int NUMBER_OF_PAGES_BEFORE_AND_AFTER = 1;
          
        public EscolasController(GestaoTarefasIPGDbContext context)
        {
            _context = context;
        }

        // GET: Escolas
        public IActionResult Index(int page = 1, string sortOrder = "Nome", string searchString = null, string searchOption = null)
        {
            decimal numberProducts = _context.Escola.Count();
            EscolasViewModel vm = new EscolasViewModel 
            {
                Escolas = _context.Escola
                .Take((int)numberProducts),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(numberProducts / NUMBER_OF_PRODUCTS_PER_PAGE),
                FirstPageShow = Math.Max(2, page - NUMBER_OF_PAGES_BEFORE_AND_AFTER),      
            };
            var searchOptionList = new List<string>();

            searchOptionList.Add("Nome");
            searchOptionList.Add("Sigla");
            searchOptionList.Add("Localizacao");
            searchOptionList.Add("Descricao");

            ViewBag.searchOption = new SelectList(searchOptionList);

            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(searchOption))
            {
                vm.CurrentSearchString = searchString;
                switch (searchOption)
                {
                    case "Nome":
                        vm.Escolas = vm.Escolas.Where(p => p.Nome.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Nome";
                        break;
                    case "Sigla":
                        vm.Escolas = vm.Escolas.Where(p => p.Sigla.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Sigla";
                        break;
                    case "Localizacao":
                        vm.Escolas = vm.Escolas.Where(p => p.Localizacao.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Localizacao";
                        break;
                    case "Descricao":
                        vm.Escolas = vm.Escolas.Where(p => p.Descricao.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Descricao";
                        break;
                }
            }
            ViewBag.NomeSortParm = sortOrder == "Nome" ? "Nome_Desc" : "Nome";
            ViewBag.SiglaSortParm = sortOrder == "Sigla" ? "Sigla_Desc" : "Sigla";
            ViewBag.LocalizacaoSortParm = sortOrder == "Localizacao" ? "Localizacao_Desc" : "Localizacao";
            ViewBag.DescricaoSortParm = sortOrder == "Descricao" ? "Descricao_Desc" : "Descricao";
            switch (sortOrder)
            {
                case "Nome_Desc":
                    vm.Escolas = vm.Escolas.OrderByDescending(p => p.Nome); 
                    vm.CurrentSortOrder = "Nome_Desc";
                    break;
                case "Sigla":
                    vm.Escolas = vm.Escolas.OrderBy(p => p.Sigla);
                    vm.CurrentSortOrder = "Sigla";
                    break;
                case "Sigla_Desc":
                    vm.Escolas = vm.Escolas.OrderByDescending(p => p.Sigla);
                    vm.CurrentSortOrder = "Sigla_Desc";
                    break;
                case "Localizacao":
                    vm.Escolas = vm.Escolas.OrderBy(p => p.Localizacao);
                    vm.CurrentSortOrder = "Localizacao";
                    break;
                case "Localizacao_Desc":
                    vm.Escolas = vm.Escolas.OrderByDescending(p => p.Localizacao);
                    vm.CurrentSortOrder = "Localizacao_Desc";
                    break;
                case "Descricao":
                    vm.Escolas = vm.Escolas.OrderBy(p => p.Descricao);
                    vm.CurrentSortOrder = "Descricao";
                    break;
                case "Descricao_Desc":
                    vm.Escolas = vm.Escolas.OrderByDescending(p => p.Descricao);
                    vm.CurrentSortOrder = "Descricao_Desc";
                    break;
                default:
                    vm.Escolas = vm.Escolas.OrderBy(p => p.Nome); // ascending by default
                    vm.CurrentSortOrder = "Nome";
                    break;

            }
            vm.TotalPages = (int)Math.Ceiling((decimal)vm.Escolas.Count() / NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.Escolas = vm.Escolas.Skip((page - 1) * NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.Escolas = vm.Escolas.Take(NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.LastPageShow = Math.Min(vm.TotalPages, page + NUMBER_OF_PAGES_BEFORE_AND_AFTER);
            vm.FirstPage = 1;
            vm.LastPage = vm.TotalPages;
            return View(vm);
        }

        // GET: Escolas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var escola = await _context.Escola
                .FirstOrDefaultAsync(m => m.EscolaID == id);
            if (escola == null)
            {
                return NotFound();
            }

            return View(escola);
        }

        // GET: Escolas/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Escolas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("EscolaID,Nome,Sigla,Localizacao,Descricao")] Escola escola)
        {
            if (ModelState.IsValid)
            {
                // se isto for null é porque não encontrou nenhum registo na tabela Escola com o mesmo Nome
                if (_context.Escola.FirstOrDefault(m => m.Nome == escola.Nome) == null)
                {
                    _context.Add(escola);
                    await _context.SaveChangesAsync();
                    return View("Sucesso");
                }
                else
                {
                    // aparece a mensagem de erro em baixo do input do Nome
                    ModelState.AddModelError("Nome", "Não é possível adicionar nomes repetidos.");
                    return View(escola);
                }
            } 
            else
            {
                return View("Erro");
            }     
        }

        // GET: Escolas/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var escola = await _context.Escola.FindAsync(id);
            if (escola == null)
            {
                return NotFound();
            }
            return View(escola);
        }

        // POST: Escolas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("EscolaID,Nome,Sigla,Localizacao,Descricao")] Escola escola)
        {
            if (id != escola.EscolaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // se isto for null é porque não encontrou nenhum registo na tabela Escola com o mesmo Nome
                    if (_context.Escola.FirstOrDefault(m => m.Nome == escola.Nome) == null)
                    {
                        _context.Update(escola);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        // aparece a mensagem de erro em baixo do input do Nome
                        ModelState.AddModelError("Nome", "Não é possível adicionar nomes repetidos.");
                        return View(escola);
                    }
;
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EscolaExists(escola.EscolaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("Sucesso");
            }
            else
            {
                return View("Erro");
            }
        }

        // GET: Escolas/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var escola = await _context.Escola
                .FirstOrDefaultAsync(m => m.EscolaID == id);
            if (escola == null)
            {
                return NotFound();
            }

            return View(escola);
        }

        // POST: Escolas/Delete/5
        [HttpPost, ActionName("Delete")]

GestaoTarefasIPG/Views/Shared/Erro.cshtml
@{
    ViewData["Title"] = "Erro";
}

<h1>Erro</h1>
<p>Algo de errado aconteceu! Tente de novo mais tarde! </p>
<a asp-action="Index" class="btn btn-dark"> Voltar</a>

GestaoTarefasIPG/Views/Shared/Sucesso.cshtml
@{
    ViewData["Title"] = "Sucesso";
}

<h1>Sucesso</h1>
<p>Operação executada com sucesso</p>
<a asp-action="Index" class="btn btn-dark"> Voltar</a>

GestaoTarefasIPG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-pt">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <meta name="description" content="Gestão de tarefas do IPG">
    <meta name="author" content="">

    <title>@ViewData["Title"]</title>

    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" /> --!>

    <!--Custom fonts-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!--Custom styles-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body id="page-top" style="margin-bottom: 0px;">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-danger sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a asp-controller="Home" asp-action="Index" class="sidebar-brand d-flex align-items-center justify-content-center">
                <div class="sidebar-brand-icon">
                    <img src="~/image/IPGlogo.png" alt="IPG logo"/>
                </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item" style="text-align:center;">

                <a asp-controller="Home" asp-action="Index" class="btn btn-light btn-lg btn-block menu">
                    <i class="fa fa-home"></i>
                    Home
                </a>
                <a asp-controller="Servicos" asp-action="Index" class="btn btn-light btn-lg btn-block menu">
                    <i class="fa fa-mobile"></i>
                    Serviços
                </a>
                <a asp-controller="Departamentos" asp-action="Index" class="btn btn-light btn-lg btn-block menu">
                    <i class="fa fa-mobile"></i>
                    Departamentos
                </a>


                @if (!User.Identity.IsAuthenticated)
                {

                }
                else
                {
                    <a asp-controller="Escolas" asp-action="Index" class="btn btn-light btn-lg btn-block menu">
                        <i class="fa fa-school"></i>
                        l       Escolas
                    </a>
                    <a asp-controller="Cargos" asp-action="Index" class="btn btn-light btn-lg btn-block menu">
                        <i class="fa fa-mobile"></i>
                        Cargos
                    </a>
                    <a asp-controller="Funcionarios" asp-action="Index" class="btn btn-light btn-lg btn-block menu">
                        <i class="fa fa-mobile"></i>
                        Funcionários
                    </a>
                }
                <a asp-controller="Home" asp-action="Contactos" class="btn btn-light btn-lg btn-block menu">
                    <i class="fa fa-book"></i>
                    Contactos
                </a>

                <!--
        <a asp-controller="Home" asp-action="About" class="btn btn-light btn-lg btn-block menu">
            <i class="fa fa-list-alt"></i>
            Sobre
        </a>
    -->
            </li>

            

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <a asp-area="Identity" asp-page="/account/login" class="btn btn-light btn-lg" style="margin-left:auto">
                            <i class="fa fa-home"></i>
                            Login
                        </a>
                    }
                    else if(User.Identity.IsAuthenticated && User.IsInRole("admin"))
                    {
                        <a asp-area="Identity" asp-page="/account/register" class="btn btn-light btn-lg" style="margin-left:auto">
                            <i class="fa fa-home"></i>
                            Criar Conta
                        </a>
                        <a asp-area="Identity" asp-page="/account/logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" class="btn btn-light btn-lg" style="margin-left:auto">
                            <i class="fa fa-home"></i>
                            Logout
                        </a>
                    }else{
                        <a asp-area="Identity" asp-page="/account/logout" class="btn btn-light btn-lg" style="margin-left:auto">
                            <i class="fa fa-home"></i>
                            Logout
                        </a>
                    }
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <div class="container">
                        <main role="main" class="pb-3">
                            @RenderBody()
                        </main>
                    </div>
                </div>
            </div>
            <!-- End of main content

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Gestão Tarefas IPG</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!--End of page wrapper-->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>

</body>
</html>

@RenderSection("Scripts", required: false)