GestaoTarefasIPG/Models/Departamento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GestaoTarefasIPG.Models
{
    public class Departamento
    {
        public int DepartamentoId { get; set; }

        [Required]
        [StringLength(40)]
        [Display(Name = "Nome:")]
        public string Nome { get; set; }

        [Display(Name = "Escola:")]
        public Escola Escola { get; set; }

        [Display(Name = "Escola:")]
        public int EscolaId { get; set; }

        public ICollection<Professor> Professores { get; set; }
    }
}

GestaoTarefasIPG/Models/DepartamentosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GestaoTarefasIPG.Models
{
    public class DepartamentosViewModel
    {
        public IEnumerable<Departamento> Departamentos { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public int FirstPageShow { get; set; }
        public int LastPageShow { get; set; }
        public int FirstPage { get; set; }
        public int LastPage { get; set; }
        public string CurrentSortOrder { get; set; }
        public string CurrentSearchOption { get; set; }
        public string CurrentSearchString { get; set; }
    }
}

GestaoTarefasIPG/Controllers/DepartamentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoTarefasIPG.Controllers
{
    public class DepartamentosController : Controller
    {
        private readonly GestaoTarefasIPGDbContext _context;

        private const int NUMBER_OF_PRODUCTS_PER_PAGE = 10;
        private const int NUMBER_OF_PAGES_BEFORE_AND_AFTER = 1;

        public DepartamentosController(GestaoTarefasIPGDbContext context)
        {
            _context = context;
        }

        // GET: Departamentos
        public IActionResult Index(int page = 1, string sortOrder = "Nome", string searchString = null, string searchOption = null)
        {
            decimal numberProducts = _context.Departamento.Count();
            var _contextDepartamento = _context.Departamento.Include(d => d.Escola);
            
            DepartamentosViewModel vm = new DepartamentosViewModel
            {
                Departamentos = _contextDepartamento
                .Take((int)numberProducts),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(numberProducts / NUMBER_OF_PRODUCTS_PER_PAGE),
                FirstPageShow = Math.Max(2, page - NUMBER_OF_PAGES_BEFORE_AND_AFTER),
            };
            var searchOptionList = new List<string>();

            searchOptionList.Add("Nome");
            searchOptionList.Add("Escola");

            ViewBag.searchOption = new SelectList(searchOptionList);

            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(searchOption))
            {
                vm.CurrentSearchString = searchString;
                switch (searchOption)
                {
                    case "Nome":
                        vm.Departamentos = vm.Departamentos.Where(p => p.Nome.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Nome";
                        break;
                    case "Escola":
                        vm.Departamentos = vm.Departamentos.Where(p => p.Escola.Nome.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Escola";
                        break;
                }
            }
            ViewBag.NomeSortParm = sortOrder == "Nome" ? "Nome_Desc" : "Nome";
            ViewBag.Nome_EscolaSortParm = sortOrder == "Nome_Escola" ? "Nome_Escola_Desc" : "Nome_Escola";         
            switch (sortOrder)
            {
                case "Nome_Desc":
                    vm.Departamentos = vm.Departamentos.OrderByDescending(p => p.Nome);
                    vm.CurrentSortOrder = "Nome_Desc";
                    break;
                case "Nome_Escola":
                    vm.Departamentos = vm.Departamentos.OrderBy(p => p.Escola.Nome);
                    vm.CurrentSortOrder = "Nome_Escola";
                    break;
                case "Nome_Escola_Desc":
                    vm.Departamentos = vm.Departamentos.OrderByDescending(p => p.Escola.Nome);
                    vm.CurrentSortOrder = "Nome_Escola_Desc";
                    break;
                default:
                    vm.Departamentos = vm.Departamentos.OrderBy(p => p.Nome); // ascending by default
                    vm.CurrentSortOrder = "Nome";
                    break;

            }
            vm.TotalPages = (int)Math.Ceiling((decimal)vm.Departamentos.Count() / NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.Departamentos = vm.Departamentos.Skip((page - 1) * NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.Departamentos = vm.Departamentos.Take(NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.LastPageShow = Math.Min(vm.TotalPages, page + NUMBER_OF_PAGES_BEFORE_AND_AFTER);
            vm.FirstPage = 1;
            vm.LastPage = vm.TotalPages;
            //return View(await gestaoTarefasIPGDbContext.ToListAsync());
            return View(vm);

        }

        // GET: Departamentos/Details/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departamento = await _context.Departamento
                .Include(d => d.Escola)
                .FirstOrDefaultAsync(m => m.DepartamentoId == id);
            if (departamento == null)
            {
                return NotFound();
            }

            return View(departamento);
        }

        // GET: Departamentos/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewData["EscolaId"] = new SelectList(_context.Escola, "EscolaID", "Nome");
            return View();
        }

        // POST: Departamentos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("DepartamentoId,Nome,EscolaId")] Departamento departamento)
        {
            if (ModelState.IsValid)
            {
                // se isto for null é porque não encontrou nenhum registo na tabela Escola com o mesmo Nome
                if (_context.Escola.FirstOrDefault(m => m.Nome == departamento.Nome) == null)
                {
                    _context.Add(departamento);
                    await _context.SaveChangesAsync();
                    return View("Sucesso");
                }
                else
                {
                    ViewData["EscolaId"] = new SelectList(_context.Escola, "EscolaID", "Nome", departamento.EscolaId);
                    // aparece a mensagem de erro em baixo do input do Nome
                    ModelState.AddModelError("Nome", "Não é possível adicionar nomes repetidos.");
                    return View(departamento);
                }
            }
            else
            {
                return View("Erro");
            }          
        }

        // GET: Departamentos/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departamento = await _context.Departamento.FindAsync(id);
            if (departamento == null)
            {
                return NotFound();
            }
            ViewData["EscolaId"] = new SelectList(_context.Escola, "EscolaID", "Nome", departamento.EscolaId);
            return View(departamento);
        }

        // POST: Departamentos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("DepartamentoId,Nome,EscolaId")] Departamento departamento)
        {
            if (id != departamento.DepartamentoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // se isto for null é porque não encontrou nenhum registo na tabela Escola com o mesmo Nome
                    if (_context.Escola.FirstOrDefault(m => m.Nome == departamento.Nome) == null)
                    {
                        _context.Update(departamento);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        ViewData["EscolaId"] = new SelectList(_context.Escola, "EscolaID", "Nome", departamento.EscolaId);
                        // aparece a mensagem de erro em baixo do input do Nome
                        ModelState.AddModelError("Nome", "Não é possível adicionar nomes repetidos.");
                        return View(departamento);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartamentoExists(departamento.DepartamentoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("Sucesso");
            }
            else
            {
                return View("Erro");
            }
        }

        // GET: Departamentos/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var departamento = await _context.Departamento
                .Include(d => d.Escola)
                .FirstOrDefaultAsync(m => m.DepartamentoId == id);
            if (departamento == null)
            {
                return NotFound();
            }

            return View(departamento);
        }

        // POST: Departamentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var departamento = await _context.Departamento.FindAsync(id);
            _context.Departamento.Remove(departamento);
            await _context.SaveChangesAsync();
            return View("Sucesso");
        }

        private bool DepartamentoExists(int id)
        {
            return _context.Departamento.Any(e => e.DepartamentoId == id);
        }
    }
}

GestaoTarefasIPG/Views/Departamentos/Create.cshtml
@model GestaoTarefasIPG.Models.Departamento

@{
    ViewData["Title"] = "Create";
}


<h1>Criar Departamento</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EscolaId" class="control-label"></label>
                <select asp-for="EscolaId" class="form-control" asp-items="ViewBag.EscolaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-dark" /> |
                <a asp-action="Index" class="btn btn-dark">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestaoTarefasIPG/Views/Departamentos/Delete.cshtml
@model GestaoTarefasIPG.Models.Departamento

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar Departamento</h1>

<h3>Têm a certeza que quer eliminar isto?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Escola)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Escola.Nome)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="DepartamentoId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-dark">Voltar</a>
    </form>
</div>

GestaoTarefasIPG/Views/Departamentos/Details.cshtml
@model GestaoTarefasIPG.Models.Departamento

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Escola)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Escola.Nome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.DepartamentoId" class="btn btn-dark">Alterar</a> |
    <a asp-action="Index" class="btn btn-dark">Voltar para a Lista</a>
</div>

GestaoTarefasIPG/Views/Departamentos/Edit.cshtml
@model GestaoTarefasIPG.Models.Departamento

@{
    ViewData["Title"] = "Edit";
}

<h1>Alterar Departamento</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DepartamentoId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EscolaId" class="control-label"></label>
                <select asp-for="EscolaId" class="form-control" asp-items="ViewBag.EscolaId"></select>
                <span asp-validation-for="EscolaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-dark" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-dark">Voltar para a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

           

GestaoTarefasIPG/Views/Departamentos/Index.cshtml
@model DepartamentosViewModel

@{
    ViewData["Title"] = "Index";
}

<div style="width: 100%; height: 80px">
    <h1 style="float: left">Departamento</h1>

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow" style="float: right; border-radius: .35rem">
        @using (Html.BeginForm("Index", "Departamentos", FormMethod.Get))
        {
            <!-- Topbar Search -->
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    @Html.DropDownList("searchOption", null, "Escolher:", new { @style = "border-radius: .35rem" })
                    &nbsp;
                    <!--<input type="text" class="form-control bg-light border-0 small" placeholder="Procure por..." aria-label="Search" aria-describedby="basic-addon2">-->
                    @Html.TextBox("searchString", null, null, new { @class = "form-control bg-light border-0 small", @style = "border-readius: .35rem", @placeholder = "Procure por ..." })
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-danger">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>
        }
    </nav>
</div>

<p>
    <a asp-action="Create" class="btn btn-dark">Criar Novo</a>
</p>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @if (Model.CurrentSortOrder == "Nome")
                {
                    <i class="fas fa-caret-up"></i>
                }
                else if (Model.CurrentSortOrder == "Nome_Desc")
                {
                    <i class="fas fa-caret-down"></i>
                }
                @Html.ActionLink("Nome:", "Index", new
                {
                    sortOrder = ViewBag.NomeSortParm,
                    page = Model.CurrentPage,
                    searchOption = Model.CurrentSearchOption,
                    searchString = Model.CurrentSearchString
                }, new { @style = "color: white" })
            </th>
            <th scope="col">
                @if (Model.CurrentSortOrder == "Nome_Escola")
                {
                    <i class="fas fa-caret-up"></i>
                }
                else if (Model.CurrentSortOrder == "Nome_Escola_Desc")
                {
                    <i class="fas fa-caret-down"></i>
                }
                @Html.ActionLink("Escola:", "Index", new
                {
                    sortOrder = ViewBag.Nome_EscolaSortParm,
                    page = Model.CurrentPage,
                    searchOption = Model.CurrentSearchOption,
                    searchString = Model.CurrentSearchString
                }, new { @style = "color: white" })
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Departamentos)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Escola.Nome)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.DepartamentoId" class="btn btn-secondary">Alterar</a> |
                    <a asp-action="Details" asp-route-id="@item.DepartamentoId" class="btn btn-secondary">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.DepartamentoId" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@*
    // TODO: Alter the functioning of the pagination interface
*@
<p>First = @Model.FirstPageShow</p>
<p>Last = @Model.LastPageShow</p>

@if (Model.FirstPage != Model.FirstPageShow)
{
    @Html.ActionLink("" + Model.FirstPage, "Index", new
    {
        sortOrder = Model.CurrentSortOrder,
        page = Model.FirstPage,
        searchOption = Model.CurrentSearchOption,
        searchString = Model.CurrentSearchString
    }, new { @class = "btn btn-secondary" })
}

@for (int i = Model.FirstPageShow; i <= Model.LastPageShow; i++)
{
    @if (i == Model.CurrentPage)
    {
        @Html.ActionLink("" + i, "#", new
        {
            sortOrder = Model.CurrentSortOrder,
            page = i,
            searchOption = Model.CurrentSearchOption,
            searchString = Model.CurrentSearchString
        }, new { @class = "btn btn-dark" })
        <text>&nbsp;</text>
    }
    else
    {
        @Html.ActionLink("" + i, "Index", new
        {
            sortOrder = Model.CurrentSortOrder,
            page = i,
            searchOption = Model.CurrentSearchOption,
            searchString = Model.CurrentSearchString
        }, new { @class = "btn btn-secondary" })
        <text>&nbsp;</text>
    }
}
@if (Model.LastPage != Model.LastPageShow)
{
    @Html.ActionLink("" + Model.LastPage, "Index", new
    {
        sortOrder = Model.CurrentSortOrder,
        page = Model.LastPage,
        searchOption = Model.CurrentSearchOption,
        searchString = Model.CurrentSearchString
    }, new { @class = "btn btn-secondary" })
}