GestaoTarefasIPG/Models/Servico.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GestaoTarefasIPG.Models
{
    public class Servico
    {
        public int ServicoId { get; set; }
        [Required(ErrorMessage = "Por favor insira um nome")]
        [StringLength(200)]
        [Display(Name = "Nome:")]
        public string Nome { get; set; }
    }
}

GestaoTarefasIPG/Models/ServicosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GestaoTarefasIPG.Models
{
    public class ServicosViewModel
    {
        public IEnumerable<Servico> Servicos { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public int FirstPageShow { get; set; }
        public int LastPageShow { get; set; }
        public int FirstPage { get; set; }
        public int LastPage { get; set; }
        public string CurrentSortOrder { get; set; }
        public string CurrentSearchOption { get; set; }
        public string CurrentSearchString { get; set; }
    }
}

GestaoTarefasIPG/Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoTarefasIPG.Controllers
{
    public class ServicosController : Controller
    {
        private readonly GestaoTarefasIPGDbContext _context;

        private const int NUMBER_OF_PRODUCTS_PER_PAGE = 10;
        private const int NUMBER_OF_PAGES_BEFORE_AND_AFTER = 1;

        public ServicosController(GestaoTarefasIPGDbContext context)
        {
            _context = context;
        }

        // GET: Servicos
        public IActionResult Index(int page = 1, string sortOrder = null, string searchString = null, string searchOption = null)
        {
            decimal numberProducts = _context.Servico.Count();
            ServicosViewModel vm = new ServicosViewModel
            {
                Servicos = _context.Servico
                .Take(NUMBER_OF_PRODUCTS_PER_PAGE),
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling(numberProducts / NUMBER_OF_PRODUCTS_PER_PAGE),
                FirstPageShow = Math.Max(1, page - NUMBER_OF_PAGES_BEFORE_AND_AFTER),
            };
            var searchOptionList = new List<string>();
            searchOptionList.Add("Nome");
            ViewBag.searchOption = new SelectList(searchOptionList);

            if (!String.IsNullOrEmpty(searchString) && !String.IsNullOrEmpty(searchOption))
            {
                vm.CurrentSearchString = searchString;
                switch (searchOption)
                {
                    case "Nome":
                        vm.Servicos = vm.Servicos.Where(p => p.Nome.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
                        vm.CurrentSearchOption = "Nome";
                        break;
                }
            }
            switch (sortOrder)
            {
                case "Nome":
                    vm.Servicos = vm.Servicos.OrderBy(p => p.Nome); // ascending by default
                    vm.CurrentSortOrder = "Nome";
                    break;
            }
            vm.TotalPages = (int)Math.Ceiling((decimal)vm.Servicos.Count() / NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.Servicos = vm.Servicos.Skip((page - 1) * NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.Servicos = vm.Servicos.Take(NUMBER_OF_PRODUCTS_PER_PAGE);
            vm.LastPageShow = Math.Min(vm.TotalPages, page + NUMBER_OF_PAGES_BEFORE_AND_AFTER);
            vm.FirstPage = 1;
            vm.LastPage = vm.TotalPages;
            return View(vm);
        }

        // GET: Servicos/Details/5
        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servico = await _context.Servico
                .FirstOrDefaultAsync(m => m.ServicoId == id);
            if (servico == null)
            {
                return NotFound();
            }

            return View(servico);
        }

        // GET: Servicos/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Servicos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("ServicoId,Nome")] Servico servico)
        {
            if (ModelState.IsValid)
            {
                // se isto for null é porque não encontrou nenhum registo na tabela Escola com o mesmo Nome
                if (_context.Servico.FirstOrDefault(m => m.Nome == servico.Nome) == null)
                {
                    _context.Add(servico);
                    await _context.SaveChangesAsync();
                    return View("Sucesso");
                }
                else
                {
                    // aparece a mensagem de erro em baixo do input do Nome
                    ModelState.AddModelError("Nome", "Não é possível adicionar nomes repetidos.");
                    return View(servico);
                }
            }
            else
            {
                return View("Erro");
            }
        }

        // GET: Servicos/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servico = await _context.Servico.FindAsync(id);
            if (servico == null)
            {
                return NotFound();
            }
            return View(servico);
        }

        // POST: Servicos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ServicoId,Nome")] Servico servico)
        {
            if (id != servico.ServicoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // se isto for null é porque não encontrou nenhum registo na tabela Escola com o mesmo Nome
                    if (_context.Servico.FirstOrDefault(m => m.Nome == servico.Nome) == null)
                    {
                        _context.Update(servico);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        // aparece a mensagem de erro em baixo do input do Nome
                        ModelState.AddModelError("Nome", "Não é possível adicionar nomes repetidos.");
                        return View(servico);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicoExists(servico.ServicoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("Sucesso");
            }
            else
            {
                return View("Erro");
            }

        }

        // GET: Servicos/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servico = await _context.Servico
                .FirstOrDefaultAsync(m => m.ServicoId == id);
            if (servico == null)
            {
                return NotFound();
            }

            return View(servico);
        }

        // POST: Servicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var servico = await _context.Servico.FindAsync(id);
            _context.Servico.Remove(servico);
            await _context.SaveChangesAsync();
            return View("Sucesso");
        }

        private bool ServicoExists(int id)
        {
            return _context.Servico.Any(e => e.ServicoId == id);
        }
    }
}

GestaoTarefasIPG/Views/Servicos/Create.cshtml
@model GestaoTarefasIPG.Models.Servico

@{
    ViewData["Title"] = "Create";
}

<h1>Criar Serviço</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-dark" /> |
                <a asp-action="Index" class="btn btn-dark">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestaoTarefasIPG/Views/Servicos/Delete.cshtml
@model GestaoTarefasIPG.Models.Servico

@{
    ViewData["Title"] = "Delete";
}

<h1>Apagar Serviço</h1>

<h3>Tem a certeza que pretende apagar isto?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ServicoId" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-dark">Voltar</a>
    </form>
</div>

GestaoTarefasIPG/Views/Servicos/Details.cshtml
@model GestaoTarefasIPG.Models.Servico

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ServicoId" class="btn btn-dark">Editar</a> |
    <a asp-action="Index" class="btn btn-dark">Voltar</a>
</div>

GestaoTarefasIPG/Views/Servicos/Edit.cshtml
@model GestaoTarefasIPG.Models.Servico

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Serviço</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ServicoId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-dark" /> |
                <a asp-action="Index" class="btn btn-dark">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestaoTarefasIPG/Views/Servicos/Index.cshtml
@*@model IEnumerable<GestaoTarefasIPG.Models.Servico>*@

@model ServicosViewModel

@{
    ViewData["Title"] = "Index";
}

<div style="width: 100%; height: 80px">
    <h1 style="float: left">Serviços</h1>

    <!-- Topbar -->
    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow" style="float: right; border-radius: .35rem">
        @using (Html.BeginForm("Index", "Servicos", FormMethod.Get))
        {
            <!-- Topbar Search -->
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    @Html.DropDownList("searchOption", null, "Escolher:", new { @style = "border-radius: .35rem" })
                    &nbsp;
                    <!--<input type="text" class="form-control bg-light border-0 small" placeholder="Procure por..." aria-label="Search" aria-describedby="basic-addon2">-->
                    @Html.TextBox("searchString", null, null, new { @class = "form-control bg-light border-0 small", @style = "border-readius: .35rem", @placeholder = "Procure por ..." })
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-danger">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>
        }
    </nav>
</div>

<p>
    <a asp-action="Create" class="btn btn-dark">Criar Novo</a>
</p>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                @Html.ActionLink("Nome:", "Index", new
                {
                        sortOrder = "Nome",
                    page = Model.CurrentPage,
                    searchOption = Model.CurrentSearchOption,
                    searchString = Model.CurrentSearchString
                }, new { @style = "color: white"})
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Servicos)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ServicoId" class="btn btn-secondary">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ServicoId" class="btn btn-secondary">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ServicoId" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model.FirstPage != Model.FirstPageShow)
{
    @Html.ActionLink("" + Model.FirstPageShow, "Index", new
    {
        sortOrder = Model.CurrentSortOrder,
        page = Model.FirstPageShow,
        searchOption = Model.CurrentSearchOption,
        searchString = Model.CurrentSearchString
    }, new { @class = "btn btn-secondary" })
}

@for (int i = Model.FirstPageShow; i <= Model.LastPageShow; i++)
{
    @if (i == Model.CurrentPage)
    {
        @Html.ActionLink("" + i, "#", new
        {
                sortOrder = Model.CurrentSortOrder,
            page = i,
            searchOption = Model.CurrentSearchOption,
            searchString = Model.CurrentSearchString
            }, new { @class = "btn btn-dark"})
        <text>&nbsp;</text>
    }
    else
    {
        {
            @Html.ActionLink("" + i, "Index", new
            {
                sortOrder = Model.CurrentSortOrder,
                page = i,
                searchOption = Model.CurrentSearchOption,
                searchString = Model.CurrentSearchString
            }, new { @class = "btn btn-secondary" })
            <text>&nbsp;</text>
        }
    }
    @if (Model.LastPage != Model.LastPageShow)
    {
        @Html.ActionLink("" + Model.LastPage, "Index", new
        {
            sortOrder = Model.CurrentSortOrder,
            page = Model.LastPage,
            searchOption = Model.CurrentSearchOption,
            searchString = Model.CurrentSearchString
        }, new { @class = "btn btn-secondary"})
    }
}